testing

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,9 +11,13 @@ jobs:
 
     steps:
       - name: Trigger PythonAnywhere deployment
-        env:
-          PA_USERNAME: ${{ secrets.USERNAME }}
-          PA_API_TOKEN: ${{ secrets.TOKEN }}
         run: |
-          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/$PA_USERNAME.pythonanywhere.com/reload/" \
-          -H "Authorization: Token $PA_API_TOKEN"
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+          "https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/webapps/${{ secrets.USERNAME }}.pythonanywhere.com/reload/" \
+          -H "Authorization: Token ${{ secrets.TOKEN }}")
+        echo "Response code: $response"
+        if [ "$response" -ne 200 ]; then
+          echo "Reload failed!"
+          exit 1
+        fi
+
